---
- name: initialize k8master
  command: kubeadm init --apiserver-advertise-address={{k8_api_ip}} --pod-network-cidr={{k8_pod_network}}

- name: cp kube admin.conf
  command: cp /etc/kubernetes/admin.conf $HOME/admin.conf

- name: chown admin.conf
  command: chown $(id -u):$(id -g) $HOME/admin.conf

- name: export KUBECONF
  command: export KUBECONFIG=$HOME/admin.conf

- name: deploy flannel network
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
