---
- name: disable selinux
  command: setenforce 0

- name: template disable selinux
  template: src=selinux.conf dest=/etc/selinux/config

- name: swap off
  command: swapoff -a

- name: comment out swap partition
  command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: br netfilter kernel
  command: modprobe br_netfilter

- name: bridge nf call iptables
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: install docker ce pre-req
  yum: name={{item}} state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: yum config manager add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce
  yum: name=docker-ce state=latest

- name: kubernetes repo copy
  template: 
    src: kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo

- name: yum install kubernetes objects
  yum: name={{item}} state=latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl
