---
- name: yum install rsyslog
  yum: name=rsyslog state=latest

- name: template rsyslog conf file
  template: src=rsyslog.conf dest=/etc/rsyslog.conf

- name: add syslog udp
  firewalld:
    port: 514/udp
    permanent: true
    state: enabled
    immediate: yes

- name: add syslog tcp
  firewalld:
    port: 514/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: systemd enable start rsyslogd
  systemd: name=rsyslog state=started enabled=yes
